papertrail/papertrail-services

services/mail.rb

Improves margins on emails, added a few media queries for better support on mobile. Gmail still doesn't respect the media queries (or any `<style>`), but everyone else will.

Email Design Tweaks

---

services/victorops.rb

This removes a leftover line that doesn't do anything anymore

Remove code refactored to source_names

---

Gemfile
Gemfile.lock

This was causing Travis builds to fail. I'm not sure the cause, but in looking into it, I noticed `master` was pointing to the latest gem release. Might as well switch to it.

Use released version of metriks-librato_metrics

---

services/cloud_watch.rb
test/cloud_watch_test.rb

Enforce the  http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/cloudwatch_limits.html limit that this class is actually going to run into (20 metrics/requests). Remove the one (request length) which, because of that limit, it will not encounter.

Add cap of 20 metrics/request and remove req length constraints

---

services/mail.rb

Noticed today that these weren't linked, while they are in non-alert emails.

Link-ify footer URLs in alert email

---

services/slack.rb
test/slack_test.rb

From the Slack API documentation:
> A plain-text summary of the attachment. This text will be used in clients that don't show formatted text (eg. IRC, mobile notifications) and should not contain any markup.
<https://api.slack.com/docs/attachments>
Without the fallback, this is what IRC clients connected to the Slack/IRC gateway see:

slack: Provide a plain-text fallback for the attachment

---

services/mail.rb

The old logo is 404ing in this email.
https://swicloud.slack.com/archives/pt-webapp/p1470441613001459

Update email to use new logo

---

services/libratometrics.rb

When reporting metrics to Librato, include the search URI as an attribute. This will allow us to link back to searches where appropriate to give people an easier transition back to logs.
/cc @snorecone @lucky @mheffner

Send search URI when reporting metric to Librato

---

services/slack.rb

We keep running into issues where Slack truncates the messages and messes up the formatting. Hopefully reducing another 500 characters will give more room to do the right thing.

Hopefully make slack not truncate messages

---

lib/papertrail_services/app.rb

Ignore some transient exceptions and log them so that we may report on trends.

Ignore some transient exceptions

---

.gitignore
Gemfile.lock
services/stathat.rb
test/stathat_test.rb

Since stathat is a metrics service, receiving counts instead of logs would make more sense and should use less resources.

Allow stathat to receive counts

---

lib/papertrail_services/helpers/logs_helpers.rb
services/mail.rb
test/mail_test.rb

Fixes #90
I also moved the `html_syslog_format` method into the helper module so that other services could use it if they so wish.

Take into account existing query string when adding additional query params to urls

---

README.md

Even though it's unnecessary, it's nice to have a prominent link to Travis.

Add the travis icon

---

services/newrelic.rb
test/newrelic_test.rb

In Insights, anything that isn't a number you can do math to should be a string :)

make ID a string since it is not an arithmetical number

---

Gemfile
Gemfile.lock

The Heroku gem is deprecated, and it doesn't seem to be serving any purpose here that I can find. It was added in [this commit to add Puma](https://github.com/papertrail/papertrail-services/commit/1ce578ae101392ac0362f9b01a4bcc780d492ca3) a long time ago.
I ran the tests, and they all passed - which doesn't mean it's safe, but it's a start :)
The advantage in removing it (besides just not having extra gems) is that installing Heroku as a gem messes up installs of the more recent Heroku toolbelt when rbenv is also in use.

remove heroku gem

---

services/datadog.rb
test/datadog_test.rb

Our example doesn't have a space, and requiring them seems unnecessary. How I see this possible change's impact:
**Pros**
* Be consistent with our example, which doesn't use spaces.
* Ignore things that should be irrelevant in this context (customers shouldn't have to care how they format their separators if we know how to do it correctly).
**Cons**
* The ~70 existing alerts that have no or inconsistent spaces in their tags will most likely see a change in behavior. Currently, if the bug report reflects the behavior correctly, these tags are not separated, but instead the `,` is converted to `_`, making one long tag. This PR would make these separate labels. It's possible that customers are currently depending on the existing labels and changing them could affect their DataDog monitoring …

do not require spaces between datadog tags

---

services/pagerduty.rb
test/pagerduty_test.rb

This fixes an issue where inactivity alerts for PagerDuty were not working because that service was expecting a payload containing events.
Example in PagerDuty:
[Diff without whitespace changes](https://github.com/papertrail/papertrail-services/pull/107/files?w=1)

Fix PagerDuty inactivity alert

---

services/hostedgraphite.rb
test/hostedgraphite_test.rb

This integration is for the [count-only webhooks ](http://help.papertrailapp.com/kb/how-it-works/web-hooks/#count-only-webhooks), this might be expanded to include all event webhooks in the future.
For the moment we will need 3 inputs from the user,
1. hostedgraphite api_key.
2. metric name
3. hostedgraphite endpoint (something like: ""https://www.hostedgraphite.com/api/v1/sink")
num1 and num2 can be found in a users account on hostedgraphite.com
Let me know what other information I need to provide, also I'm not a regular ruby coder so apologies if there's any stupid mistakes in here.

Adding a hostedgraphite integration to papertrail.

---

Gemfile
Gemfile.lock
services/pushover.rb
test/pushover_test.rb

This fixes an issue where inactivity alerts for Pushover were not working because that service was expecting a payload containing events. Also removed Rushover gem so payloads are testable and to closer match how other services send requests.
Example Pushover inactivity alert:

Fix Pushover inactivity alert

---

services/mail.rb

This is an extension of the previous header add to include the upcoming address change in the body, so that Gmail/Google Apps can work with it for filtering, with reference to the scheduled maintenance at http://www.papertrailstatus.com/incidents/7xfb65y1tkk5.

initial add of new address to mail body

---

services/datadog.rb

`counter` is a deprecated type, and is also treated as a rate in the Datadog UI, per https://help.datadoghq.com/hc/en-us/articles/206955236-Metric-types-in-Datadog; Papertrail counts aren't rates.
The Datadog API prefers `gauge` type, and gauge metrics will display counts corresponding to those seen in Papertrail when visualized with the correct settings. 
Prior to production change it'll be determined whether this affects existing metrics in Datadog.

use gauge type for Datadog metric

---

services/mail.rb

Complete the change to the new alert address. To be merged Sept 12, per http://www.papertrailstatus.com/incidents/7xfb65y1tkk5.

New from address, remove information from transition period

---

services/mail.rb

This should look pretty much like the version at https://github.com/papertrail/papertrail-services/commit/b5b5bf02850011898fac2ed49f7a84f92c9fff24, but with updated wording so that people can figure out what changed from the email itself.

add back footer about recent change

---

Gemfile
Gemfile.lock

Fixes Moscow tz (changed in 2014) and probably other things, without changing major releases.

update tzinfo to latest 0.3 series

---

services/mail.rb

This week it'll be about a month since we made the email address change. It's been pretty seamless, so I think it's time to remove the reminder.

remove email address change info

---

services/mail.rb

This should curb the need for most ticketing system-type destinations to send auto-replies when they receive alert emails from Papertrail.

Add auto-generated header to outgoing emails

---

lib/papertrail_services/app.rb

Adds some custom metrics in the form of Heroku logs. We'll use a custom drain to send these to AppOptics

Add notify AO metric

---

services/cloud_watch.rb
services/sns.rb
test/cloud_watch_test.rb

Prevent these three AWS errors from filling up our Sentry quota.

Rescue AWS errors without logging to Sentry
